- index.js
- test.js
Fixes #9
As described in #9, it's possible for the data stored inside of the config file to become inaccurate. This could make it look like we should attempt to resume an upload, when in fact, there isn't an upload to resume and instead, we should be restarting one.
Instead of always returning a 404 from the `continueUploading` process (i.e., the server tells us "That's not a file, what are you talking about?"), we will only return that error if the user gave us the resumable URI themselves. When we use the config file to get the URI, we'll just assume that means we failed to clean up after ourselves (or some other uncontrollable event intervened) and we can safely restart the upload.
@richardkazuomiller PTAL (please take a look)!
> delete config when it is probably wrong

- index.js
- test.js
> support 410 restarts

- package.json
- src/cli.ts
- src/index.ts
- test/test.ts
Don't let the size fool you, this is super boring. Mostly just running `gts fix` :)
> chore: gts fix and more types

- package.json
- src/cli.ts
- src/index.ts
- test/system-tests/kitchen.ts
- test/test.ts
- tsconfig.json
> chore: enable noImplicitAny

- readme.md
- src/index.ts
- test/test.ts
@JustinBeckwith sorry if this makes a nightmare for #53. This is needed for https://github.com/googleapis/nodejs-storage/pull/179!
> Add support for KMS Keys

- package.json
- src/index.ts
- test/fixtures/keys.json
- test/system-tests/kitchen.ts
- test/test.ts
This should be done as a rebase commit :)
> Merge `next` into `master`

- src/cli.ts
- test/system-tests/kitchen.ts
- test/test.ts
This is like 99% home :)  I'm having some struggles figuring out the failing kitchen sink test.  Ready for a first look.
> chore: re-work some of the tests

- CHANGELOG.md
- package.json
> Release gcs-resumable-upload v0.13.0

- .github/ISSUE_TEMPLATE.md
- package.json
- samples/package.json
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> Update to new repo location

- samples/package.json
- samples/quickstart.js
- src/index.ts
- test/test.ts
> feat: add progress events

- .gitignore
- .prettierignore
- .prettierrc
- renovate.json
- synth.metadata
- synth.py
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> chore: update synth and common config

- CHANGELOG.md
- package.json
- samples/package.json
> Release gcs-resumable-upload v0.14.0

- CHANGELOG.md
- package.json
- samples/package.json
> Release gcs-resumable-upload v0.14.1

- CHANGELOG.md
- package.json
- samples/package.json
> Release gcs-resumable-upload v1.0.0

- package.json
- src/cli.ts
- src/index.ts
- system-test/kitchen.ts
- test/test.ts
test to see whether a new PR gets us out of the failed CI/CD runs [here](https://github.com/googleapis/gcs-resumable-upload/pull/208).
> build: upgrade gts and other dependencies for 2.x release

- package.json
- test/test.ts
fix exponential back off unit test with sinon.spy
> refactor: exponential back off unit test

- .jsdoc.js
- samples/quickstart.js
- samples/system-test/system.js
- src/cli.ts
- src/index.ts
- system-test/kitchen.ts
- test/test.ts
Builds were getting mad about these license headers!
> chore: update license headers

- src/index.ts
- system-test/kitchen.ts
- test/test.ts
> fix: set custom config file path

- src/index.ts
- system-test/kitchen.ts
- test/test.ts
Fixes #221 (it's a good idea to open an issue first for discussion)
> fix: typecast metadata.size from string to number

- README.md
Added Progress Event Description in readme file.
Fixes #311
> fix(docs): progress event in readme file 

- package.json
> chore(dep): deprecate Node 8
