- index.js
- readme.md
- test.js
The JSON api supports [resuming an interrupted upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#resume-upload). This PR changes the `Content-Range` header to match the resuming protocol.
Closes #11
> Make the 	Content-Range header configurable

- index.js
- test.js
Considering the following case:
-- I provide a resumable upload URI
-- I provide an offset
We were overwriting that in [`continueUploading`](https://github.com/stephenplusplus/gcs-resumable-upload/blob/700d60b26a96b465140bd79cb2135f772842017a/index.js#L127). That function is called as soon as data is written to the gcs-resumable-upload stream (https://github.com/stephenplusplus/gcs-resumable-upload/blob/700d60b26a96b465140bd79cb2135f772842017a/index.js#L64-L66). Within `continueUploading`, it always gets the offset from the API, and ends up overwriting what the user gave.
@bhstahl could you let me know if I'm wrong about any of that ^^ and if this change doesn't break anything. Thanks!
> respect a given offset when resuming

- .gitignore
- package.json
Updates dependencies that allow tunnel-agent <= 0.6.0, which has a memory exposure vuln.
> Update request and google-auto-auth

- index.js
- test.js
This fixes issues when using resumable uploads targeted towards
different buckets. The resumable URI will be for the wrong bucket if
there's an in-progress upload to a different bucket with the same
filename.
> Use bucket/file for configStore key

- .circleci/config.yml
RE: https://github.com/stephenplusplus/gcs-resumable-upload/pull/34#issuecomment-378684678
In Circle, we use an encrypted env var to decode the JSON key file. It is not exposed to forked PRs, thus Circle doesn't even try to run the tests when the key decryption step fails.
This is a temporary solution to simply always run the test commands, even when the decrypt fails. Having some failing tests (the ones that use the service account) is okay-- we'll at least see if any other new bugs were introduced.
After #34 / when it is convenient to start messing with code (don't want to interrupt what @JustinBeckwith is going through), I'll find a better way to do this, possibly a simple `if (/* is CirclePR */) { skip test }`
> circle: run tests even if key decrypt failed

- package.json
- src/index.ts
- test/test.ts
Turns out you don't need this with Node.js 4 and up 😸
> chore: remove buffer-equal

- package.json
- src/index.ts
- test/test.ts
This is going to be important when we look at switching to axios.  This switches up a few of the tests to use nock instead of stubbing `request` calls.  It also standardizes the types used for Request type stuff, meaning less churn in the tests when we change stuff.
> test: use nock for tests

- package.json
- src/index.ts
- test/system-tests/kitchen.ts
- test/test.ts
This breaks the API in 2 ways. First - since we're moving to es modules, there's no real way to just export the function as the default export. Second, since we are already breaking the API, I detached createURI from the upload method, and just split it out into its own function.
If we do a semver major release, I'd also like to get the axios and google-auth-library changes in that release as well.  
@ofrobots @stephenplusplus what do you think?
> feat: upgrade to es modules

- package.json
[Release Notes](https://github.com/stephenplusplus/gcs-resumable-upload/releases/edit/untagged-7c78d483d2f22d28e032)
> chore: release 0.11.0

- src/cli.ts
- src/index.ts
- src/types.ts
- test/system-tests/kitchen.ts
- test/test.ts
This change makes sure that `axios` types don't leak into the `index.d.ts`.
> fix: quarantine axios types

- CHANGELOG.md
- package.json
Current version breaks downstream packages, namely `nodejs-storage` (because of noSyntheticDefaultImports).
> Release gcs-resumable-upload v0.12.0

- package.json
- src/index.ts
- test/test.ts
This adds support for async functions on the public `createURI` method, and also ensures the rest of the code is async first.
> feat: support async functions

- src/index.ts
- test/test.ts
The previous code was taking a GaxiosError, which is an object, and passing it into the constructor of a generic Error class. Error classes are only meant to receive a string, so the error being returned to the user was `[object Object]`. This just returns the Gaxios error directly!
> fix: return GaxiosError directly

- README.md
- src/index.ts
- test/test.ts
RE: #4
This introduces the `configPath` option. This allows a user to explicitly state where the ConfigStore config file will be stored.
> feat: support ConfigStore configPath option

- CHANGELOG.md
- package.json
- samples/package.json
> Release gcs-resumable-upload v1.1.0

- package.json
- src/index.ts
- test/test.ts
This does a few things:
- Adds the `apiEndpoint` config option, making it overridable
- Updates the default endpoint to use `storage.googleapis.com`
- Swaps out `nyc` for `c8` since coverage appeared to be broken
> feat: support apiEndpoint override

- README.md
- src/index.ts
RE: https://github.com/googleapis/nodejs-storage/issues/217
This simply makes the `deleteConfig()` method public, so stale data in the cache file can be removed by a user.
> feat: allow removing cache file

- README.md
- src/index.ts
- test/test.ts
Fixes https://github.com/googleapis/nodejs-storage/issues/217
When a user attempts an upload, this lib checks a cache file to see if it should resume a previously-failed attempt, or start a new one. This system previously failed if a user started an upload, it failed, then they tried again with a new generation. That was because the cache file persisted data about each file based on a key in the format of "bucketName/fileName". Now, it will be "bucketName/fileName/generation".
> fix: make cache key unique by including generation

- src/index.ts
- test/test.ts
Towards finding the cause of googleapis/nodejs-storage/issues/675
> fix: expose 'Retry limit exceeded' server error message

- src/index.ts
- test/test.ts
> fix: handle a `0` generation

- package.json
- src/index.ts
- system-test/kitchen.ts
- test/test.ts
Fixes https://github.com/googleapis/nodejs-storage/issues/811
When we call the API to query the status of a resumable upload operation, we have been letting gaxios consider all API responses a success. This change makes sure that only the 308 status (resumable upload incomplete) is excused, since we handle that from this library.
> fix: let gaxios handle API errors

- src/index.ts
- test/test.ts
Fixes #7
This allows the user to pass in all of the available query parameter options allowed by the API: https://cloud.google.com/storage/docs/json_api/v1/objects/insert#parameters
Currently, we alias only the ones we need from @google-cloud/storage. This PR keeps those aliases, but also accepts them through a new `config.params` property.
> feat: support all query parameters during URI creation

- system-test/kitchen.ts
- system-test/util.ts
`should resume an interrupted upload` appears to sometimes fail due to upstream API issues.
> test: handle flaky upstream failures

- src/index.ts
- test/test.ts
Required for https://github.com/googleapis/nodejs-storage/pull/1161.
This allow user to specify a protocol before `apiEndpoint`, for use with a local emulator etc..
`new upload({apiEndpoint: 'http://fake.googleapis.com'});`
protocol-less apiEndpoint is still accepted (which will default to appending `https://` in front of the url).
This allows us to support the same behaviour in nodejs-storage: https://github.com/googleapis/nodejs-storage/pull/1161
> feat: allow user-specified protocol for options.apiEndpoint

- README.md
- package.json
- src/index.ts
- test/test.ts
This allows a user to define custom request options, e.g. custom headers, when instantiating a gcs-resumable-upload instance.
> feat: allow custom request options
